<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="10188" started-at="2018-09-09T07:20:36Z" finished-at="2018-09-09T07:20:47Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="241" started-at="2018-09-09T07:20:36Z" finished-at="2018-09-09T07:20:37Z">
      <class name="com.accenture.tests.MyTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.accenture.tests.MyTest@7113b13f]" name="beforeTest" is-config="true" duration-ms="15" started-at="2018-09-09T07:20:37Z" finished-at="2018-09-09T07:20:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="Registration()[pri:0, instance:com.accenture.tests.MyTest@7113b13f]" name="Registration" duration-ms="22" started-at="2018-09-09T07:20:37Z" finished-at="2018-09-09T07:20:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.accenture.tests.MyTest.Registration(MyTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.accenture.tests.MyTest@7113b13f]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-09-09T07:20:37Z" finished-at="2018-09-09T07:20:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.accenture.tests.MyTest@7113b13f]" name="loginTest" duration-ms="0" started-at="2018-09-09T07:20:37Z" finished-at="2018-09-09T07:20:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.accenture.tests.MyTest -->
    </test> <!-- Test -->
    <test name="Test1" duration-ms="9635" started-at="2018-09-09T07:20:37Z" finished-at="2018-09-09T07:20:47Z">
      <class name="com.accenture.tests.Login">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.accenture.tests.Login@8646db9]" name="beforeTest" is-config="true" duration-ms="3378" started-at="2018-09-09T07:20:37Z" finished-at="2018-09-09T07:20:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:com.accenture.tests.Login@8646db9]" name="testLogin" duration-ms="6256" started-at="2018-09-09T07:20:40Z" finished-at="2018-09-09T07:20:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
      </class> <!-- com.accenture.tests.Login -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
